version: "3.8"

services:
  pyarmor-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./source:/app/source
      - ./obfuscated:/app/obfuscated
    working_dir: /app
    # entrypoint: ["sh", "-c", "pyarmor gen -r --output=/app/obfuscated /app/source"]
    command: ["python", "/app/obfuscated/source/sample.py"]
